/*

 BG_BOTTOM.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 4
   Tile set      : R:\NintendoDev\gbdk\proj\Overgrowth\Overgrowth-GBJAM10\sprites\bg_image8x8_2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bg_bottom_mapWidth 8
#define bg_bottom_mapHeight 4
#define bg_bottom_mapBank 0

unsigned char bg_bottom_map[] =
{
  0x00,0x02,0x08,0x0A,0x10,0x12,0x18,0x1A,0x01,0x03,
  0x09,0x0B,0x11,0x13,0x19,0x1B,0x04,0x06,0x0C,0x0E,
  0x14,0x16,0x1C,0x1E,0x05,0x07,0x0D,0x0F,0x15,0x17,
  0x1D,0x1F
};

/* End of BG_BOTTOM.C */
