/*

 BG_BOTTOM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 4
   Tile set      : R:\NintendoDev\gbdk\proj\Overgrowth\Overgrowth-GBJAM10\sprites\bg_image8x8_2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bg_bottom_mapWidth 8
#define bg_bottom_mapHeight 4
#define bg_bottom_mapBank 0

extern unsigned char bg_bottom_map[];

/* End of BG_BOTTOM.H */
