/*

 BG_LVL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 24
   Tile set      : R:\NintendoDev\gbdk\proj\Overgrowth\Overgrowth-GBJAM10\sprites\bg_level_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_bg_lvl1Width 100
#define map_bg_lvl1Height 24
#define map_bg_lvl1Bank 0

extern unsigned char map_bg_lvl1[];

/* End of BG_LVL1.H */
