/*

 DOORS.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define door_defaultBank 0
extern unsigned char door_defaultTLE0[];
extern unsigned char door_defaultTLE1[];
extern unsigned char door_defaultTLE2[];
extern unsigned char door_defaultTLE3[];

/* End of DOORS.H */
